name: Auto label PR
on: pull_request_target
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(owner:$owner)
            console.log(name:$name)
            console.log(context.payload.pull_request.self)
            console.log(context.payload.pull_request.number)
            console.log(context.repo.owner)
            console.log(context.repo.repo)
