name: Auto label PR
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // console.log(context.payload.pull_request.number)
            // console.log(context.payload.pull_request.commits)
            const url = context.payload.pull_request.url
            const pull_request = await github.request(url)
            console.log(pull_request.data)
            //console.log(pull_request.data[0].url)
            //const commit = await github.request(url)
            //console.log(commit.data)

