name: Auto label PR
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // console.log(context.payload.pull_request.number)
            // console.log(context.payload.pull_request.commits)
            const pull_request = await github.request(context.payload.pull_request.url)
            console.log({pull_request: pull_request.data})
            const pull_request_issue = await github.request(context.payload.pull_request.issues_url)
            console.log({pull_request_issue: pull_request_issue.data})
            const pull_request_events = await github.request(pull_request_issue.data.events_url)
            console.log({events: pull_request_events.data})
            const graphql_response = await github.graphql('query { viewer { login } }')
            console.log({graphql_response: graphql_response})

            
            //console.log(pull_request.data[0].url)
            //const commit = await github.request(url)
            //console.log(commit.data)

