name: Auto label PR
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload.pull_request.number)
            console.log(context.payload.pull_request.commits)
            const url = context.payload.pull_request.commits_url
            const result = await github.request(url)
            console.log(result)
            console.log(result.data)
            console.log(result.data[0].commit)
            console.log(result.data[0].url)
