name: Auto label PR
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // console.log(context.payload.pull_request.number)
            // console.log(context.payload.pull_request.commits)
            const pull_request = await github.request(context.payload.pull_request.url)
            //console.log({pull_request: pull_request.data})
            console.log({pull_request: pull_request.data.html_url})

            const graphql_response = await github.graphql('{ resource(url: "' + pull_request.data.html_url + '") { ... on PullRequest { timelineItems(itemTypes: [CONNECTED_EVENT, DISCONNECTED_EVENT], first: 100) { nodes { ... on ConnectedEvent { id subject { ... on Issue { number }}} ... on DisconnectedEvent { id subject { ... on Issue { number }}}}}}}}')
            console.log({graphql_response: graphql_response.resource.timelineItems})

            
            //console.log(pull_request.data[0].url)
            //const commit = await github.request(url)
            //console.log(commit.data)

